name = "hono-react-ssr-shadcn-ui"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-22"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
BLOG_USERNAME="admin"
BLOG_PASSWORD="123456"

[[kv_namespaces]]
binding = "blog"
id = "49618aedf53541fe924c656cdb360f9d"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
